kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend
  # labels:
  #   app: frontend-deployment

spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      # name: frontend-pod
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend
          image: ghcr.io/acm-mu/abacus/frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
