apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: node-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-pod
  template:
    metadata:
      name: node-pod
      labels:
        app: node-pod
    spec:
      containers:
        - name: abacus-server
          image: ghcr.io/acm-mu/abacus-backend:sha-021e2b3
          imagePullPolicy: Always
          ports:
            - containerPort: 80
