kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend
  # labels:
  #   app: node-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      # name: node-pod
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: ghcr.io/acm-mu/abacus/backend
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
