version: 0.0
os: linux 
files:
  - source: index.py
    destination: /app
  - source: abacus
    destination: /app/abacus
hooks:
  BeforeInstall:
    - location: .aws/codedeploy-scripts/deleteAndKill.sh
      runas: root
  ApplicationStart:
    - location: .aws/codedeploy-scripts/applicationStart.sh
      runas: root