version: "3.8"

services:
  mongodb:
    container_name: mongo
    restart: unless-stopped
    build:
      context: .docker
      dockerfile: Dockerfile.mongo
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - 27017:27017
  server:
    container_name: server
    restart: unless-stopped
    build:
      context: backend
      dockerfile: Dockerfile.prod
    environment:
      - MONGO_HOST=mongo:27017
      - MONGO_USER=username
      - MONGO_PASS=password
      - MONGO_DBNAME=abacus
    ports:
      - "80:80"

