version: "3.7"

services:
  mongo:
    container_name: mongo
    restart: unless-stopped
    build:
      context: .docker
      dockerfile: Dockerfile.mongo
    environment:
      - MONGO_HOST=mongo
      - MONGO_USER=admin
      - MONGO_PASS=password
      - MONGO_DBNAME=abacus
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - "27017-27019:27017-27019"
  server:
    container_name: server
    restart: unless-stopped
    build:
      context: backend
      dockerfile: Dockerfile.prod
    ports:
      - "8080:80"
    depends_on:
      - mongo
  app:
    container_name: app
    build:
      context: frontend
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    depends_on:
      - server
