version: "3.8"

services:
  mongodb:
    container_name: mongo
    restart: unless-stopped
    build:
      context: .docker
      dockerfile: Dockerfile.mongo
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - 27017:27017
  server:
    container_name: server
    restart: unless-stopped
    build:
      context: backend
      dockerfile: Dockerfile.prod
    environment:
      - MONGO_HOST=mongodb
      - MONGO_USER=MUad
      - MONGO_PASS=ep16y11BPqP
      - MONGO_DBNAME=admin
    ports:
      - "8080:80"
    depends_on:
      - mongodb
  app:
    container_name: app
    build:
      context: frontend
      dockerfile: Dockerfile.prod
    volumes:
      - ./frontend/abacus.crt:/etc/nginx/ssl/abacus.crt 
      - ./frontend/abacus.key:/etc/nginx/ssl/abacus.key
    ports:
      - "80:80"
    depends_on:
      - server
