version: "3.7"
services:
  app:
    env_file: .env
    container_name: abacus
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 80:80
    volumes: 
      - .:/app
