version: "3.8"

services:
  mongodb:
    container_name: mongo
    restart: unless-stopped
    build:
      context: .docker
      dockerfile: Dockerfile.mongo
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - '27017:27017'
  piston:
    container_name: piston
    build:
      context: .docker
      dockerfile: Dockerfile.piston
    volumes:
      - './piston-volume:/piston'
    tmpfs:
      - '/piston/jobs:exec'
    ports:
      - '2000:2000'
  server:
    container_name: server
    restart: unless-stopped
    build:
      context: backend
      dockerfile: Dockerfile.prod
    environment:
      - MONGO_HOST=mongodb
      - MONGO_USER=username
      - MONGO_PASS=password
      - MONGO_DBNAME=abacus
    ports:
      - "8080:80"
    depends_on:
      - mongodb
  app:
    container_name: app
    build:
      context: frontend
      dockerfile: Dockerfile.prod
    ports:
      - "8081:80"
    depends_on:
      - server
