version: "3.8"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports: 
      - "8080:80"
      - "443:443"
    volumes:
      - ./frontend:/frontend
    depends_on:
      - server
      - app
  mongodb:
    container_name: mongo
    restart: unless-stopped
    build:
      context: .docker
      dockerfile: Dockerfile.mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=MUad
      - MONGO_INITDB_ROOT_PASSWORD=ep16y11BPqP
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - 27017:27017
  server:
    container_name: server
    restart: unless-stopped
    build:
      context: backend
      dockerfile: Dockerfile.prod
    environment:
      - MONGO_HOST=mongo:27017
      - MONGO_USER=MUad
      - MONGO_PASS=ep16y11BPqP
      - MONGO_DBNAME=abacus
    deploy:
      resources: 
        reservations:
          cpus: '10'
          memory: "12GB"
    ports:
      - "80:80"
    depends_on:
      - mongodb
  app:
    container_name: app
    restart: unless-stopped
    build:
      context: frontend
    volumes:
      - ./frontend/public:/app/public
      - ./frontend/src:/app/src
    ports:
      - "3000:3000"
    depends_on:
      - server