version: "3.7"
services:
  app:
    env_file: .env
    container_name: abacus
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 80:80
    volumes: 
      - .:/app
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-2
        awslogs-group: ec2-abacus
        awslogs-create-group: "true"
        awslogs-datetime-format: '\[%b %d, %Y %H:%M:%S\]'
