version: "3.8"

services:
  mongodb:
    container_name: mongo
    restart: unless-stopped
    build:
      context: .docker
      dockerfile: Dockerfile.mongo
    volumes:
      - ./mongo-volume:/data/db
    command: mongod --bind_ip=127.0.0.1,mongo
  server:
    container_name: server
    restart: unless-stopped
    build:
      context: backend
      dockerfile: Dockerfile.prod
      network: host
    environment:
      - MONGO_HOST=mongodb
      - MONGO_USER=MUad
      - MONGO_PASS=ep16y11BPqP
      - MONGO_DBNAME=admin
    ports:
      - "8080:80"
    depends_on:
      - mongodb
  app:
    container_name: app
    build:
      context: frontend
      dockerfile: Dockerfile.prod
      network: host
    ports:
      - "80:80"
    depends_on:
      - server
