version: 0.0
os: linux
files:
  - source: /
    destination: /app
hooks:
  ApplicationStop:
    - location: ./scripts/stop.sh
      runas: root
  BeforeInstall:
    - location: ./scripts/install.sh
      runas: root
  ApplicationStart:
    - location: ./scripts/start.sh
      runas: root
