version: 0.0
os: linux
files:
  - source: /backend/*
    destination: /app
hooks:
  ApplicationStop:
    - location: ./stop.sh
      runas: root
  ApplicationStart:
    - location: ./start.sh
      runas: root
