name: Build and deploy backend
on:
  push:
    paths:
      - "backend/**"
    branches:
      - "master"
jobs:
  deploy:
    name: CI/CD Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - uses: egordm/gha-yarn-node-cache@v1

      - name: Install dependencies from package.json
        run: yarn install
        working-directory: backend

      - name: Build project
        run: yarn build
        working-directory: backend

      - name: Package project into zip file
        run: yarn run zip
        working-directory: backend

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload zip file to codedeploy s3 bucket
        run: aws s3 cp dist/backend.zip "s3://codeabac.us-codedeploy/${{ github.sha }}.zip"
        working-directory: backend

      - name: Create new elastic beanstalk application version with zip file
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name abacus-backend \
          --source-bundle S3Bucket="codeabac.us-codedeploy",S3Key="${{ github.sha }}.zip" \
          --version-label "ver-${{ github.sha }}" \
          --description "commit-sha-${{ github.sha }}"

      - name: Deploy new application version
        run: aws elasticbeanstalk update-environment --environment-name abacus-backend-prod --version-label "ver-${{ github.sha }}" && aws elasticbeanstalk update-environment --environment-name abacus-backend-stage --version-label "ver-${{ github.sha }}"
