FROM mongo

COPY ./init-mongo.js /docker-entrypoint-initdb.d/init-mongo.js

HEALTHCHECK --interval=10s --timeout=10s --start-period=40s --retries=5 CMD [ "echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet" ]

EXPOSE 27017