
import "semantic-ui-css/semantic.min.css"
import "./app.scss"
import "./table.scss"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="abacus">
        {children}
      </body>
    </html>
  )
}
