export { default as AdminNavigation } from './admin.navigation'
export { default as BlueNavigation } from './blue.navigation'
export { default as EagleNavigation } from './eagle.navigation'
export { default as GoldNavigation } from './gold.navigation'
export { default as JudgeNavigation } from './judge.navigation'
export { default as ProctorNavigation } from './proctor.navigation'
export { default as DefaultNavigation } from './default.navigation'