name: Prettify Frontend
on:
  push:
    paths: ["frontend/**"]

jobs:
  prettier:
    name: Prettify Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: creyD/prettier_action@v4.0
        with:
          prettier_options: --write --config frontend/.prettierrc.js frontend/**/*
