name: Prettify Code
on:
  push:
    paths:
      - 'backend/**'
      - 'frontend/**'
    branches:
      - '*'
      - '!master'

jobs:
  prettier:
    name: Prettify Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write {backend/src,frontend/src}/**/*.{ts,tsx,scss}
