name: Deploy JavaCompiler lambda
on:
  push:
    paths:
      - "lambdas/JavaCompiler/*"
    branches:
      - "master"
jobs:
  deploy_zip:
    name: CD Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1

      - name: Package source into zip file
        working-directory: lambdas/JavaCompiler
        run: zip -r JavaCompiler.zip .

      - name: Deploy zip file to lambda
        working-directory: lambdas/JavaCompiler
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: JavaCompiler
          zip_file: JavaCompiler.zip
