name: Build and deploy backend
on:
  push:
    # paths:
    #   - "backend/*"
    branches:
      - "react"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install dependencies
        working-directory: backend
        run: npm install

      - name: Build project
        working-directory: backend
        run: npm run build

      - name: Compress project
        working-directory: backend
        run: tar -czvf ./backend.tar.gz ./dist

      - name: Upload project
        working-directory: backend
        run: aws s3 cp ./backend.tar.gz s3://codeabac.us-backend

      - name: Deploy project
        uses: aws-actions/aws-codebuild-run-build@v1.0.3
        with:
          project-name: CodeAbacus-Backend
