name: Deploy PistonRunner Lambda
on:
  push:
    paths:
      - "lambdas/PistonRunner/PistonRunner.js"
    branches:
      - "master"
jobs:
  deploy_bluerunner:
    name: deploy PistonRunner
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: PistonRunner
          source: lambdas/PistonRunner/PistonRunner.js
