name: Deploy PistonRunner lambda
on:
  push:
    paths:
      - "lambdas/PistonRunner/*"
    branches:
      - "master"
jobs:
  deploy_bluerunner:
    name: CD Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1

      - name: Package source into zip file
        run: cd lambdas/PistonRunner && zip PistonRunner.zip PistonRunner.js

      - name: Deploy zip file to lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: PistonRunner
          zip_file: PistonRunner.js
