name: Create and publish Abacus piston

on:
  push:
    branches: ['master']
    paths:
      - 'piston/**'

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    name: Build and Push Docker image to Github Packages
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Login to GitHub registry
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: piston/api
          file: piston/api/Dockerfile
          push: true
          pull: true
          tags: ghcr.io/acm-mu/abacus/piston
